<?php

/**
 * @file
 * @todo.
 */

/**
 * Implements hook_module_implements_alter().
 */
function gsb_workbench_save_and_publish_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter') {
    // Allow gsb_workbench_save_and_publish_form_node_form_alter to run last.
    if (isset($implementations['gsb_workbench_save_and_publish'])) {
      $group = $implementations['gsb_workbench_save_and_publish'];
      unset($implementations['gsb_workbench_save_and_publish']);
      $implementations['gsb_workbench_save_and_publish'] = $group;
    }

    // We really need submit field to be last so it picks up our changes above.
    if (isset($implementations['submit_field'])) {
      $group = $implementations['submit_field'];
      unset($implementations['submit_field']);
      $implementations['submit_field'] = $group;
    }
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for node_form().
 */
function gsb_workbench_save_and_publish_form_node_form_alter(&$form, &$form_state, $form_id) {
  $form['actions']['save_and_publish'] = array(
    '#type' =>  'submit',
    '#value' => t('Save & Publish'),
    '#weight' => 6,
    '#submit' => $form['actions']['submit']['#submit'],
  );

  // Add our own submit method to the top.
  array_unshift($form['actions']['save_and_publish']['#submit'], 'gsb_workbench_save_and_publish_submit');

  // Change Save button to say Save As Draft.
  $form['actions']['submit']['#value'] = t('Save As Draft');
}

/**
 * Form submission handler for the node form.
 */
function gsb_workbench_save_and_publish_submit($form, &$form_state) {
  $form_state['values']['workbench_moderation_state_new'] = 'published';
}
